name: Push to S3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: npm install && npm run build

      # 👇 Store the dist folder
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # 👇 Get the dist folder
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync app-build s3://portfolio-app-rjomega --delete
