name: Push to S3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: ./portfolio_app
        run: npm install && npm run build

      - name: Display structure of before files
        run: ls -R

      # 👇 Store the dist folder
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./portfolio_app/build/

      - name: Display structure of after files
        run: ls -R

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Test content
        run: ls -R

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./portfolio_app/build


      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://portfolio-app-rjomega --delete

